#!/bin/sh
#
#  Copyright (C) 2016 Peter Kenji Yamanaka
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

main()
{
        local c=
        for i in $(seq 0 9); do
                c=$(tr -cd "0-9a-f" < /dev/urandom | fold -bw 6 | sed 1q)
                printf "*color%d:  #%s\n" "$i" "$c"
        done
        for i in $(seq 10 15); do
                c=$(tr -cd "0-9a-f" < /dev/urandom | fold -bw 6 | sed 1q)
                printf "*color%d: #%s\n" "$i" "$c"
        done
        unset c
}

main
