#!/usr/bin/env sh

set -eu
set -o pipefail

function print_spaces()
{
        for I in $(seq 1 $(expr 14 + ${#t})); do
                printf " "
        done
}

function print_padded_labels()
{
        for num in 40m 41m 42m 43m 44m 45m 46m 47m; do
                printf "%s" "${num}"
                for I in $(seq 1 $(expr ${#t} + 2)); do
                        printf " "
                done
        done
}

function print_colors()
{
        echo
        for fgcs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
                '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
                '  36m' '1;36m' '  37m' '1;37m'; do
                local fgc=${fgcs// /}
                printf " %s \033[%s  %s  " "${fgcs}" "${fgc}" "$t"
                for bgc in 40m 41m 42m 43m 44m 45m 46m 47m; do
                        printf " \033[%s\033[%s  %s  \033[0m" \
                                "${fgc}" "${bgc}" "$t"
                done
                echo
                unset fgc
        done
}

function main()
{
        local t=   # The test text
        if [ $# -eq 0 ]; then
                t='gYw'
        else
                t=$1
        fi

        print_spaces
        print_padded_labels
        print_colors

        unset t
}

main
